### ISSUE TITLE
Custom resolvers limits is not correct

### ISSUE THREAD

**Issue by csulrong** [ibm-cloud-docs/dns-svcs#3]
https://cloud.ibm.com/docs/dns-svcs?topic=dns-svcs-custom-resolver&interface=ui#cr-limits

> Each custom resolver can have a maximum of 15 forwarding rules.

The right maximum number of forwarding rules should be 10.

**Comment by Sandeepad3118** [comment]
@sheltons Can you update the docs with correct details. Thanks

**Comment by sheltons** [comment]
update pushed. Closing.
