### ISSUE TITLE
Customer feedback

### ISSUE THREAD

**Issue by austinmama** [ibm-cloud-docs/dns-svcs#5]
From: Ronan Doolan 

It would be useful if there was a tutorial on this which included the zone and dns services creation

Also, I changed the anchor back to the original version for this topic:  https://cloud.ibm.com/docs/dns-svcs?topic=dns-svcs-create-linked-zone&interface=ui 

There was a **Learn more** link that had a broken link from this anchor change: https://github.com/ibm-cloud-docs/dns-svcs/commit/0559fe6d1feefbe4b492f1cd7af21c59f80e5256

**Comment by sheltons** [comment]
Moved issue to staging repo to work on it there. Thanks!
