### ISSUE TITLE
Open a Support case to enable the total metrics set. With what team exactly?

### ISSUE THREAD

**Issue by gridhawk** [ibm-cloud-docs/dns-svcs#7]
Open a Support case to enable the total metrics set. With what team exactly? AppDev (Sysdig) or Network support?

Steps to enable/activate this feature: https://cloud.ibm.com/docs/dns-svcs?topic=dns-svcs-monitor-ibm-cloud-pm#metrics_dictionary-pm (https://cloud.ibm.com/docs/metrics-router?topic=metrics-router-cloud-services-mr#networking)

**Comment by sheltons** [comment]
It's the Network support team. Documentation for DNS Services has been updated.
